// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "chineseHealthy/apps/app/api/internal/handler/article"
	image "chineseHealthy/apps/app/api/internal/handler/image"
	medicine "chineseHealthy/apps/app/api/internal/handler/medicine"
	"chineseHealthy/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/look/all_articles",
				Handler: article.LookAllArticlesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: image.ImageCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updata",
				Handler: image.ImageUpdataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: image.ImageDeleteHandler(serverCtx),
			},
		},
		rest.WithPrefix("/image"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: medicine.MedicineCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: medicine.MedicineDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/find",
				Handler: medicine.MedicineFindHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mod",
				Handler: medicine.MedicineModHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vague",
				Handler: medicine.LookMedicineHandler(serverCtx),
			},
		},
		rest.WithPrefix("/medicine"),
	)
}
