// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package articleclient

import (
	"context"

	"chineseHealthy/apps/article/rpc/types/article"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleInfo             = article.ArticleInfo
	LookAllArticlesRequest  = article.LookAllArticlesRequest
	LookAllArticlesResponse = article.LookAllArticlesResponse

	Article interface {
		LookAllArticles(ctx context.Context, in *LookAllArticlesRequest, opts ...grpc.CallOption) (*LookAllArticlesResponse, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

func (m *defaultArticle) LookAllArticles(ctx context.Context, in *LookAllArticlesRequest, opts ...grpc.CallOption) (*LookAllArticlesResponse, error) {
	client := article.NewArticleClient(m.cli.Conn())
	return client.LookAllArticles(ctx, in, opts...)
}
