// Code generated by goctl. DO NOT EDIT.
package types

type MedicineInfo struct {
	Id                uint64       `json:"id"`
	Name              string       `json:"name"`
	Alias             string       `json:"alias"`
	Taste             string       `json:"taste"`
	Meridian          string       `json:"meridian"`
	Efficacy          string       `json:"efficacy"`
	UsageDosage       string       `json:"usageDosage"`
	Contraindications string       `json:"contraindications"`
	ImageInfo         []*ImageInfo `json:"imageInfo"`
}

type ImageInfo struct {
	Id         int64  `json:"id"`
	MedicineId int64  `json:"MedicineId"`
	Url        string `json:"url"`
}

type MedicineCreateInfo struct {
	Name              string `json:"name"`
	Alias             string `json:"alias"`
	Taste             string `json:"taste"`
	Meridian          string `json:"meridian"`
	Efficacy          string `json:"efficacy"`
	UsageDosage       string `json:"usageDosage"`
	Contraindications string `json:"contraindications"`
}

type ImageCreateRequest struct {
	MedicineId uint64   `json:"medicineId"`
	Urls       []string `json:"urls"`
}

type ImageCreateResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ImageUpdataResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type ImageDelRequest struct {
	Id uint64 `json:"id"`
}

type ImageDelResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MedicineCreateRequest struct {
	Data *MedicineCreateInfo `json:"data"`
}

type MedicineCreateResponse struct {
	Code    int64        `json:"code"`
	Message string       `json:"message"`
	Data    MedicineInfo `json:"data"`
}

type MedicineDelRequest struct {
	Id uint64 `json:"id"`
}

type MedicineDelResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MedicineFindRequest struct {
	Id uint64 `json:"id"`
}

type MedicineFindResponse struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    *MedicineInfo `json:"data"`
}

type LookMedicineVagueRequest struct {
	Key string `json:"key"`
}

type LookMedicineVagueResponse struct {
	Data []*MedicineInfo `json:"data"`
}

type MedicineModRequest struct {
	Data *MedicineInfo `json:"data"`
}

type MedicineModResponse struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    *MedicineInfo `json:"data"`
}

type ArticleInfo struct {
	Id      uint32 `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Image   string `json:"image"`
	Author  string `json:"author"`
}

type LookAllArticleRequest struct {
}

type LookAllArticleResponse struct {
	Data []*ArticleInfo `json:"data"`
}
