// Code generated by goctl. DO NOT EDIT.
package types

type MedicineInfo struct {
	Id                uint64   `json:"id"`
	Name              string   `json:"name"`
	Alias             string   `json:"alias"`
	Taste             string   `json:"taste"`
	Meridian          string   `json:"meridian"`
	Efficacy          string   `json:"efficacy"`
	UsageDosage       string   `json:"usageDosage"`
	Contraindications string   `json:"contraindications"`
	ImageUrls         []string `json:"imageUrls"`
}

type ImageCreateRequest struct {
	MedicineId uint64   `json:"medicineId"`
	Urls       []string `json:"urls"`
}

type ImageCreateResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type ImageDelRequest struct {
	Id uint64 `json:"id"`
}

type ImageDelResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MedicineCreateRequest struct {
	Data *MedicineInfo `json:"data"`
}

type MedicineCreateResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MedicineDelRequest struct {
	Id uint64 `json:"id"`
}

type MedicineDelResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MedicineFindRequest struct {
	Id uint64 `json:"id"`
}

type MedicineFindResponse struct {
	Code    int64         `json:"code"`
	Message string        `json:"message"`
	Data    *MedicineInfo `json:"data"`
}

type MedicineModRequest struct {
	Data *MedicineInfo `json:"data"`
}

type MedicineModResponse struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}
