// Code generated by goctl. DO NOT EDIT.
// Source: medicine.proto

package server

import (
	"context"

	"chineseHealthy/apps/medicine/rpc/internal/logic"
	"chineseHealthy/apps/medicine/rpc/internal/svc"
	"chineseHealthy/apps/medicine/rpc/types/medicine"
)

type MedicineServer struct {
	svcCtx *svc.ServiceContext
	medicine.UnimplementedMedicineServer
}

func NewMedicineServer(svcCtx *svc.ServiceContext) *MedicineServer {
	return &MedicineServer{
		svcCtx: svcCtx,
	}
}

func (s *MedicineServer) MedicineCreate(ctx context.Context, in *medicine.MedicineCreateRequest) (*medicine.MedicineCreateResponse, error) {
	l := logic.NewMedicineCreateLogic(ctx, s.svcCtx)
	return l.MedicineCreate(in)
}

func (s *MedicineServer) MedicineDel(ctx context.Context, in *medicine.MedicineDelRequest) (*medicine.MedicineDelResponse, error) {
	l := logic.NewMedicineDelLogic(ctx, s.svcCtx)
	return l.MedicineDel(in)
}

func (s *MedicineServer) MedicineMod(ctx context.Context, in *medicine.MedicineModRequest) (*medicine.MedicineModResponse, error) {
	l := logic.NewMedicineModLogic(ctx, s.svcCtx)
	return l.MedicineMod(in)
}

func (s *MedicineServer) MedicineFind(ctx context.Context, in *medicine.MedicineFindRequest) (*medicine.MedicineFindResponse, error) {
	l := logic.NewMedicineFindLogic(ctx, s.svcCtx)
	return l.MedicineFind(in)
}

func (s *MedicineServer) ImageCreate(ctx context.Context, in *medicine.ImageCreateRequest) (*medicine.ImageCreteResponse, error) {
	l := logic.NewImageCreateLogic(ctx, s.svcCtx)
	return l.ImageCreate(in)
}

func (s *MedicineServer) ImageDelete(ctx context.Context, in *medicine.ImageDelRequest) (*medicine.ImageDelResponse, error) {
	l := logic.NewImageDeleteLogic(ctx, s.svcCtx)
	return l.ImageDelete(in)
}

func (s *MedicineServer) FindMedicine(ctx context.Context, in *medicine.FindMedicineRequest) (*medicine.FindMedicineResponse, error) {
	l := logic.NewFindMedicineLogic(ctx, s.svcCtx)
	return l.FindMedicine(in)
}
