// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"chineseHealthy/apps/medicine/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/image/create",
				Handler: ImageCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/image/delete",
				Handler: ImageDeleteHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/medicine/create",
				Handler: MedicineCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/medicine/delete",
				Handler: MedicineDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/medicine/find",
				Handler: MedicineFindHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/medicine/mod",
				Handler: MedicineModHandler(serverCtx),
			},
		},
	)
}
