// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"chineseHealthy/apps/article/rpc/internal/logic"
	"chineseHealthy/apps/article/rpc/internal/svc"
	"chineseHealthy/apps/article/rpc/types/article"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	article.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) LookAllArticles(ctx context.Context, in *article.LookAllArticlesRequest) (*article.LookAllArticlesResponse, error) {
	l := logic.NewLookAllArticlesLogic(ctx, s.svcCtx)
	return l.LookAllArticles(in)
}
